version: '3.8'

services:
  redis:
    image: redis:latest  # Use the latest Redis image
    ports:
      - "6379:6379"  # Map port 6379 from the container to your host
    volumes:
      - redis-data:/data  # Persistent data storage

volumes:
  redis-data:  # Persistent volume for Redis data
